version: '3.8'
services:
  # Cloud Read-Write PACS HTTP only
  cloud-rw-pacs:
    build: cloud-rw-pacs
    ports:
      - "8042:8042"
    environment:
      TRANSFERS_PLUGIN_ENABLED: "true"
      ORTHANC__NAME: "cloud-rw-pacs"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__ENABLE: "true"
      ORTHANC__DICOM_WEB__ROOT: "/dicom-web/"
      PYTHON_PLUGIN_ENABLED: "true"
      ORTHANC__PYTHON_SCRIPT: "/etc/orthanc/anonymize.py"
      ORTHANC__PYTHON_VERBOSE: "true"
      ORTHANC__REGISTERED_USERS: |
        { "admin" : "secure-password" }
    restart: unless-stopped
    env_file:
      - common-pacs.env
